// let's imagine this file is autogenerated from the backend
// ideally, we want to keep these api related types in sync
// with the backend instead of manually writing them out

export type BaseEntity = {
  id: string;
  createdAt: number;
};

export type Entity<T> = {
  [K in keyof T]: T[K];
} & BaseEntity;

export type Meta = {
  page: number;
  total: number;
  totalPages: number;
};

// User roles matching backend enum
export type UserRole =
  | 'Admin'
  | 'ClusterManager'
  | 'Supervisor'
  | 'Farmer'
  | 'AgronomyExpert'
  | 'UavVendor';

export type User = Entity<{
  firstName: string;
  lastName: string;
  email: string;
  role: UserRole;
  teamId: string;
  bio: string;
}>;

// Backend Result wrapper
export type Result<T> = {
  succeeded: boolean;
  data: T;
  message?: string;
  errors?: string[];
};

// Token data from login/refresh endpoints
export type TokenData = {
  accessToken: string;
  refreshToken: string;
  expiresAt: string; // ISO date string
};

// Login response
export type LoginResponse = {
  accessToken: string;
  refreshToken: string;
  expiresAt: string;
  user: User;
};

// Legacy type for backward compatibility
export type AuthResponse = {
  jwt: string;
  user: User;
};

export type Team = Entity<{
  name: string;
  description: string;
}>;

export type Discussion = Entity<{
  title: string;
  body: string;
  teamId: string;
  author: User;
}>;

export type Comment = Entity<{
  body: string;
  discussionId: string;
  author: User;
}>;

// Material Management Types
export enum MaterialType {
  Fertilizer = 0,
  Pesticide = 1,
}

export type Material = {
  materialId: string;
  name: string;
  type: MaterialType;
  ammountPerMaterial: number;
  unit: string;
  showout: string;
  pricePerMaterial: number;
  description: string;
  manufacturer: string;
  isActive: boolean;
};

// PagedResult<T> from backend - extends Result<T> with pagination
export type PagedResult<T> = {
  succeeded: boolean;
  data: T;
  currentPage: number;
  totalPages: number;
  totalCount: number;
  pageSize: number;
  hasPrevious: boolean;
  hasNext: boolean;
  message?: string;
  errors?: string[];
};

// Rice Variety Management Types
export type RiceVarietyCategory = {
  id: string;
  name: string;
  description?: string;
};

export type RiceVariety = {
  id: string;
  varietyName: string;
  categoryId: string;
  categoryName: string;
  baseGrowthDurationDays: number;
  baseYieldPerHectare: number;
  description: string;
  characteristics: string;
  isActive: boolean;
};

export type ChangeRiceSeasonRequest = {
  riceId: string;
  seasonId: string;
};

export type DownloadRiceVarietiesRequest = {
  inputDate: string;
  categoryId?: string;
  isActive?: boolean;
};

// Season Management Types
export type Season = {
  id: string;
  seasonName: string;
  startDate: string; // MM/DD format
  endDate: string; // MM/DD format
  seasonType: string; // e.g., "Winter-Spring", "Summer-Autumn"
  isActive: boolean;
  createdAt: string;
};

// Rice Variety Season Association Types
export type RiceVarietySeasonAssociation = {
  id: string;
  riceVarietyId: string;
  riceVarietyName: string;
  seasonId: string;
  seasonName: string;
  growthDurationDays: number;
  expectedYieldPerHectare: number;
  optimalPlantingStart: string; // MM/DD format
  optimalPlantingEnd: string; // MM/DD format
  riskLevel: number; // 0=Low, 1=Medium, 2=High
  seasonalNotes?: string;
  isRecommended: boolean;
  createdAt: string;
};

export type RiceVarietyWithSeasons = RiceVariety & {
  associatedSeasons?: RiceVarietySeasonAssociation[];
};

// Material CRUD Types
export type CreateMaterialRequest = {
  name: string;
  type: MaterialType;
  ammountPerMaterial: number;
  unit: string;
  pricePerMaterial: number;
  description?: string;
  manufacturer?: string;
  isActive: boolean;
  priceValidFrom: string;
};

export type UpdateMaterialRequest = {
  materialId: string;
  name: string;
  type: MaterialType;
  ammountPerMaterial: number;
  unit: string;
  pricePerMaterial: number;
  description?: string;
  manufacturer?: string;
  isActive: boolean;
  priceValidFrom: string;
};

// Rice Variety CRUD Types
export type CreateRiceVarietyRequest = {
  varietyName: string;
  categoryId: string;
  baseGrowthDurationDays: number;
  baseYieldPerHectare: number;
  description?: string;
  characteristics?: string;
  isActive: boolean;
};

export type UpdateRiceVarietyRequest = {
  riceVarietyId: string;
  varietyName: string;
  categoryId: string;
  baseGrowthDurationDays: number;
  baseYieldPerHectare: number;
  description?: string;
  characteristics?: string;
  isActive: boolean;
};

// Season CRUD Types
export type CreateSeasonRequest = {
  seasonName: string;
  startDate: string; // MM/DD format
  endDate: string; // MM/DD format
  seasonType: string;
  isActive: boolean;
};

export type UpdateSeasonRequest = {
  seasonId: string;
  seasonName: string;
  startDate: string; // MM/DD format
  endDate: string; // MM/DD format
  seasonType: string;
  isActive: boolean;
};

// Rice Variety Season Association CRUD Types
export type CreateRiceVarietySeasonRequest = {
  riceVarietyId: string;
  seasonId: string;
  growthDurationDays: number;
  expectedYieldPerHectare: number;
  optimalPlantingStart: string; // MM/DD format
  optimalPlantingEnd: string; // MM/DD format
  riskLevel: number;
  seasonalNotes?: string;
  isRecommended: boolean;
};

export type UpdateRiceVarietySeasonRequest = {
  riceVarietySeasonId: string;
  growthDurationDays: number;
  expectedYieldPerHectare: number;
  optimalPlantingStart: string; // MM/DD format
  optimalPlantingEnd: string; // MM/DD format
  riskLevel: number;
  seasonalNotes?: string;
  isRecommended: boolean;
};

// Standard Plan Types
export type StandardPlan = {
  id: string;
  name: string;
  description?: string;
  categoryId: string;
  categoryName: string;
  totalDuration: number;
  isActive: boolean;
  totalTasks: number;
  totalStages: number;
  createdAt: string;
  createdBy: string;
  lastModified: string;
  lastModifiedBy: string;
};

export type StandardPlanTask = {
  id: string;
  taskName: string;
  sequenceOrder: number;
  taskType: string;
  priority: string;
  description?: string;
  materials: any[]; // Material usage details
};

export type StandardPlanStage = {
  id: string;
  stageName: string;
  sequenceOrder: number;
  expectedDurationDays: number;
  isMandatory: boolean;
  notes?: string;
  tasks: StandardPlanTask[];
};

export type StandardPlanDetail = {
  id: string;
  planName: string;
  description?: string;
  totalDurationDays: number;
  isActive: boolean;
  categoryId: string;
  categoryName: string;
  createdBy: string;
  creatorName: string;
  createdAt: string;
  lastModified: string;
  stages: StandardPlanStage[];
  totalStages: number;
  totalTasks: number;
  totalMaterialTypes: number;
};

export type StandardPlanReview = {
  standardPlanId: string;
  planName: string;
  description?: string;
  categoryId: string;
  categoryName: string;
  sowDate: string;
  areaInHectares: number;
  estimatedStartDate: string;
  estimatedEndDate: string;
  totalDurationDays: number;
  estimatedTotalCost: number;
  estimatedCostPerHectare: number;
  stages: StandardPlanStage[];
  totalStages: number;
  totalTasks: number;
  totalMaterialTypes: number;
  totalMaterialQuantity: number;
};

export type UpdateStandardPlanRequest = {
  standardPlanId: string;
  planName: string;
  description?: string;
  totalDurationDays: number;
  isActive: boolean;
};

export type DownloadStandardPlansRequest = {
  inputDate: string;
  categoryId?: string;
  isActive?: boolean;
};

// Task and Project Types for Farmer UI
export type TaskStatus = 'To-do' | 'In Progress' | 'Completed' | 'Done';

export type Task = Entity<{
  title: string;
  projectName: string;
  projectId: string;
  status: TaskStatus;
  scheduledTime?: string; // Time in HH:mm format
  scheduledDate: string; // Date in ISO format
  description?: string;
  priority?: 'Low' | 'Medium' | 'High';
  category?: string;
  progress?: number; // 0-100
}>;

export type TaskGroup = {
  id: string;
  name: string;
  icon?: string;
  color?: string;
};

export type Project = Entity<{
  name: string;
  description?: string;
  taskGroupId: string;
  taskGroupName: string;
  startDate: string; // ISO date string
  endDate: string; // ISO date string
  logo?: string;
  brandColor?: string;
  totalTasks: number;
  completedTasks: number;
  progress: number; // 0-100
}>;

export type CreateProjectRequest = {
  name: string;
  description?: string;
  taskGroupId: string;
  startDate: string; // ISO date string
  endDate: string; // ISO date string
  logo?: string;
  brandColor?: string;
};

// Farmer-specific Types
export type Field = Entity<{
  name: string;
  area: number; // in hectares
  cropVarietyId: string;
  cropVarietyName: string;
  plantingDate: string; // ISO date string
  coordinates?: {
    latitude: number;
    longitude: number;
  };
  polygon?: Array<{ latitude: number; longitude: number }>; // For GIS map
}>;

export type FarmerPlot = {
  plotId: string;
  area: number;
  soThua: number;
  soTo: number;
  status: string;
  groupId: string;
  groupName: string;
  activeCultivations: number;
  activeAlerts: number;
  boundary: string | null;
  coordinate: string; // "POINT (lat lng)" or "POINT (lng lat)" depending on backend
};

export type PlotCultivationPlan = {
  plotCultivationId: string;
  seasonId: string;
  seasonName: string;
  riceVarietyId: string;
  riceVarietyName: string;
  plantingDate: string;
  area: number | null;
  status: string;
  actualYield?: number | null;
  productionPlanName: string;
};

export type FarmerMaterialComparison = {
  materialId: string;
  materialName: string;
  materialUnit: string;
  plannedQuantityPerHa: number;
  plannedEstimatedAmount: number;
  actualQuantity: number;
  actualCost: number;
};

export type PlotPlanTask = {
  id: string;
  taskName: string;
  description?: string | null;
  taskType: string;
  scheduledDate: string;
  status: string;
  priority: string;
  isContingency: boolean;
  actualMaterialCost?: number | null;
  materials: FarmerMaterialComparison[];
};

export type PlotPlanStage = {
  stageName: string;
  sequenceOrder: number;
  tasks: PlotPlanTask[];
};

export type PlotPlanView = {
  plotCultivationId: string;
  productionPlanId: string;
  planName: string;
  basePlantingDate: string;
  planStatus: string;
  plotArea: number;
  stages: PlotPlanStage[];
};

export type FarmActivity = Entity<{
  fieldId: string;
  fieldName: string;
  activityType: 'planting' | 'fertilizing' | 'spraying' | 'irrigation' | 'harvesting';
  date: string; // ISO date string
  materialId?: string;
  materialName?: string;
  quantity: number;
  unit: string;
  cost: number; // Calculated from material price
  notes?: string;
  photos?: string[]; // Photo URLs
}>;

export type Alert = Entity<{
  type: 'pest' | 'weather' | 'recommendation';
  severity: 'low' | 'medium' | 'high' | 'critical';
  title: string;
  message: string;
  fieldId?: string;
  fieldName?: string;
  pestType?: string;
  recommendedTreatment?: string;
  approved: boolean;
  createdAt: string;
}>;

export type FarmerTask = Entity<{
  title: string;
  description?: string;
  taskType: 'spraying' | 'fertilizing' | 'harvesting' | 'irrigation' | 'other';
  fieldId: string;
  fieldName: string;
  scheduledDate: string; // ISO date string
  scheduledTime?: string; // HH:mm format
  status: 'pending' | 'in-progress' | 'completed';
  completedDate?: string;
  completionPhotos?: string[];
  planId?: string;
}>;

export type EconomicPerformance = {
  seasonId: string;
  seasonName: string;
  totalCost: number;
  totalRevenue: number;
  profit: number;
  profitPerHectare: number;
  fields: Array<{
    fieldId: string;
    fieldName: string;
    area: number;
    cost: number;
    revenue: number;
    profit: number;
  }>;
};

// Today's Tasks Types
export type TodayTaskMaterialResponse = {
  materialId: string;
  materialName: string;
  materialUnit: string;
  plannedQuantityTotal: number;
  estimatedAmount: number;
};

export type TodayTaskResponse = {
  cultivationTaskId: string;
  plotCultivationId: string;
  taskName: string;
  description?: string | null;
  taskType: string;
  status: string;
  scheduledDate: string;
  priority: string;
  isOverdue: boolean;
  plotSoThuaSoTo: string;
  plotArea: number;
  estimatedMaterialCost: number;
  materials: TodayTaskMaterialResponse[];
};

export type TaskMaterialDetailResponse = {
  materialId: string;
  materialName: string;
  materialUnit: string;
  plannedQuantityPerHa: number;
  plannedTotalEstimatedCost: number;
  actualQuantityUsed: number;
  actualCost: number;
  logNotes?: string | null;
};

export type FarmLogSummaryResponse = {
  farmLogId: string;
  loggedDate: string;
  completionPercentage: number;
  actualAreaCovered?: number | null;
  workDescription?: string | null;
  photoUrls?: string[];
  actualServiceCost?: number | null;
};

export type CultivationTaskDetailResponse = {
  cultivationTaskId: string;
  plotCultivationId: string;
  taskName: string;
  description?: string | null;
  taskType: string;
  status: string;
  priority: string;
  isContingency: boolean;
  plannedScheduledDate: string;
  actualStartDate?: string | null;
  actualEndDate?: string | null;
  estimatedMaterialCost: number;
  actualMaterialCost: number;
  actualServiceCost: number;
  plotName: string;
  plotArea: number;
  materials: TaskMaterialDetailResponse[];
  farmLogs: FarmLogSummaryResponse[];
};

// Farm Log Types
export type FarmLogMaterialRequest = {
  materialId: string;
  actualQuantityUsed: number;
  notes?: string | null;
};

export type CreateFarmLogRequest = {
  cultivationTaskId: string;
  plotCultivationId: string;
  workDescription?: string | null;
  actualAreaCovered?: number | null;
  serviceCost?: number | null;
  serviceNotes?: string | null;
  weatherConditions?: string | null;
  interruptionReason?: string | null;
  proofImages?: string[]; // Array of image URIs (will be converted to FormData)
  materials?: FarmLogMaterialRequest[];
  farmerId?: string | null;
};

// Report/Alert Types
export type AlertType = 'Pest' | 'Weather' | 'Disease' | 'Other';
export type ReportSeverity = 'Low' | 'Medium' | 'High' | 'Critical';
export type ReportStatus = 'Pending' | 'UnderReview' | 'Resolved' | 'Rejected';

export type CreateReportRequest = {
  plotCultivationId?: string | null;
  groupId?: string | null;
  clusterId?: string | null;
  alertType: AlertType;
  title: string;
  description: string;
  severity: ReportSeverity;
  imageUrls?: string[];
};

export type ReportResponse = {
  id: string;
  plotId: string;
  plotName: string;
  plotArea: number;
  cultivationPlanId: string;
  cultivationPlanName: string;
  reportType: AlertType;
  severity: ReportSeverity;
  title: string;
  description: string;
  reportedBy: string;
  reportedByRole: string;
  reportedAt: string;
  status: ReportStatus;
  images: string[];
  coordinates: string;
  resolvedBy: string | null;
  resolvedAt: string | null;
  resolutionNotes: string | null;
  farmerName: string;
  clusterName: string;
};

export type GetMyReportsParams = {
  currentPage?: number;
  pageSize?: number;
  searchTerm?: string;
  status?: ReportStatus;
  severity?: ReportSeverity;
  reportType?: AlertType;
};